name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install coveralls
          pip install responses
          pip install -r requirements.txt
      - name: Run tests and collect coverage
      - uses: dennisjensen95/coverage-scope@v0.5.0
        with: 
          coverage-filepath: cobertura.xml
          branch: main
