name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COVERAGE_SINGLE: 60
      COVERAGE_TOTAL: 60
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.12
      uses: actions/setup-python@main
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install honeybadger
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: coverage
      uses: paambaati/codeclimate-action@v8.0.0
      env:
         CC_TEST_REPORTER_ID: a74feccb5078454467bec3580569397c08fd150796dd7878f223143160892772
      with:
         coverageCommand: npm run coverage
         debug: true


         
