name: scan

on:
  push

jobs:
  code-scanning:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     
     - name: check for vulnerabilities
       uses: mdegis/bandit-action@v1.0
       with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          level: high
          confidence: high
          exit_zero: true
